In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
df = pd.read_csv('train.txt',sep=';',header = None,names = ['text','emotion'])

In [28]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [29]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [30]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}

In [31]:
for i in range(len(unique_emotions)):
    emotion_numbers[unique_emotions[i]] = i+1

emotion_numbers

{'sadness': 1, 'anger': 2, 'love': 3, 'surprise': 4, 'fear': 5, 'joy': 6}

In [32]:
df['emotion'] = df['emotion'].map(emotion_numbers)

In [33]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        1
1  i can go from feeling so hopeless to so damned...        1
2   im grabbing a minute to post i feel greedy wrong        2
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        2

In [36]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [37]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        1
1  i can go from feeling so hopeless to so damned...        1
2   im grabbing a minute to post i feel greedy wrong        2
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        2

In [39]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [41]:
df['text'] = df['text'].apply(remove_punc)

In [42]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [43]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [44]:
import nltk

In [59]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [60]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vyass\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vyass\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [65]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vyass\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [66]:
stop_words = set(stopwords.words('english'))

In [67]:
len(stop_words)

198

In [68]:
def remove(txt):
  words = word_tokenize(txt)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [69]:
df['text'] = df['text'].apply(remove)

In [70]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [72]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.7678125

In [73]:

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [74]:
y_pred = nb2_model.predict(X_test_tfidf)

In [75]:
print(accuracy_score(y_test, y_pred))

0.6609375

In [76]:
from sklearn.linear_model import LogisticRegression

In [77]:
logistic_model = LogisticRegression(max_iter=1000)

In [78]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [80]:
log_pred = logistic_model.predict(X_test_tfidf)
print(accuracy_score(y_test,log_pred ))

0.8615625